### ISSUE TITLE
Crash when trying moor_shared demo on my android device

### ISSUE THREAD

**Issue by jims57** [rodydavis/moor_shared#11]
When using on my physical Android device, it crashed as follows:
![image](https://user-images.githubusercontent.com/1920873/85640088-68b52e80-b6bd-11ea-9beb-538c930d940b.png)
The device is using Android 7.1.2:
![image](https://user-images.githubusercontent.com/1920873/85640286-06106280-b6be-11ea-8100-b4414562ccb7.png)

But, it work fine on the Android emulator running on the MacOS:
![image](https://user-images.githubusercontent.com/1920873/85640176-a3b76200-b6bd-11ea-9b4e-63a09e6b9ce7.png)

My question is whether **moor** requires the minimum version of Android to make it works? If yes, I hope to make it support as extent as possible when it comes to Android version, because our product will meet users with different background.

Will **Moor** save the stack trace in a file on the device? If yes, please tell me where, so that I can send you it.

Am I missing anything before I release the code to a physical device? Thanks.

**Comment by rodydavis** [comment]
@simolus3 is there a limitation?

**Comment by simolus3** [comment]
`moor_ffi` should work on all Android versions supported by Flutter.

@jims57 You can view the stacktrace using a tool like [logcat](https://developer.android.com/studio/command-line/logcat).

**Comment by rodydavis** [comment]
Seems unrelated to this plugin. Please file an issue on the flutter repo if possible. 

Sounds like there may be a permission issue.

**Comment by jims57** [comment]
@ro

> Seems unrelated to this plugin. Please file an issue on the flutter repo if possible.
> 
> Sounds like there may be a permission issue.

@rodydavis I have raised a [bug](https://github.com/flutter/flutter/issues/60458) to them, please don't close this issue, for it may be related to **moor_shared**.

**Comment by jims57** [comment]
The problem is unrelated to both **Moor** and **Moor_Shared**. I shouldn't copy directly the debug apk built on MacOS based Android Studio to the physical Android device which has different CPU architecture.
What I should do is to build a fat apk which includes binaries for android-arm, android-arm64, android-x64.

![image](https://user-images.githubusercontent.com/1920873/85985090-c2e72400-ba1c-11ea-9952-25b56a9660ec.png)
