### ISSUE TITLE
Can you update code to the lasted methods to replace the deprecated ones?

### ISSUE THREAD

**Issue by jims57** [rodydavis/moor_shared#12]
![image](https://user-images.githubusercontent.com/1920873/85944932-e0f54b80-b96c-11ea-9d5b-091ce0754704.png)

**Comment by bostone** [comment]
Also rewriting this to use recommended `moor:ffi` would be marvelous

**Comment by rodydavis** [comment]
FFI wouldn't work in the browser though. But the desktop and mobile could use it

**Comment by rodydavis** [comment]
I'm open to PRs! It should run on all platforms

**Comment by bostone** [comment]
I would love to pitch in however see my [bug I just opened]([url](https://github.com/rodydavis/moor_shared/issues/14))

**Comment by bostone** [comment]
> FFI wouldn't work in the browser

Whoa - I did not realize that. Can these two used side by side in the same project? To be honest I'm only interested in running iOS/Android/web

**Comment by rodydavis** [comment]
Fixed!
