### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by nadimgouia** [rodydavis/moor_shared#5]
unfortunately its not working on windows

**Comment by rodydavis** [comment]
You may have to recreate the windows folder with the latest from desktop embedding. It changes quite often.

If you get it working please make a PR. I can’t test windows easily.

**Comment by tomaszpolanski** [comment]
@nadimgouia Could you try out if the PR that I've created compiles now for you. 
I have noticed that now there is ffi issue that I will try to investigate

**Comment by rodydavis** [comment]
FFI issue for Windows?

**Comment by tomaszpolanski** [comment]
It cannot load dynamically the library on Windows by throwing `Invalid argument(s): Failed to load dynamic library (193)`

**Comment by tomaszpolanski** [comment]
Apparently error `193` is when I am using 32-bit dll for 64-bit library. 
I've downloaded [the 64-bit version](https://sqlite.org/2020/sqlite-dll-win64-x64-3310100.zip) and I've put it either in the root of the project (when running the project from IntelliJ) or at the same folder as the `.exe` file of the compiled version of the project is.
Now it works as expected - just need to think how to bundle the dll in the project

**Comment by tomaszpolanski** [comment]
One way boundle it would be to add the dll to `assets` folder and `pubspec.yaml`:
```
flutter:
  assets:
    - assets/sqlite3.dll
```
And then change in `moor_ffi` function `_defaultOpen` so for Windows it would return `DynamicLibrary.open('data/flutter_assets/assets/sqlite3.dll');`.
This, unfortunately, needs to be done on `moor_ffi` side

**Comment by rodydavis** [comment]
Ok thank you! @simolus3 may know better

**Comment by simolus3** [comment]
It should be possible to override the dlopen in `moor_ffi` with something like this:
```dart
import 'package:moor_ffi/open_helper.dart';

void main() { // or anywhere else, before opening the database
  open.overrideFor(OperatingSystem.windows, _openOnWindows);
}

DynamicLibrary _openOnWindows() {
  return DynamicLibrary.open('data/flutter_assets/assets/sqlite3.dll');
}
```

In older `moor_ffi` versions this didn't work, but on `0.3.1`  or later it should. So maybe just upgrading to `moor_ffi: ^0.4.0` and writing an open override should do the trick?

**Comment by tomaszpolanski** [comment]
Thanks @simolus3. That would have worked. After investigation, adding the dll inside of assets would have included it in all the builds (macOs,...). 
I've created a PR that adds the dll in windows compilation process
