### ISSUE TITLE
Error: The non-abstract class 'TodoEntry' is missing implementations for these members

### ISSUE THREAD

**Issue by jims57** [rodydavis/moor_shared#8]
It worked good before I upgrade **moor** and **moor_ffi** to the latest version.
I think this is caused by the different APIs among these version. Can you update this project to support the latest version of **moor** and **moor_ffi**, since I'd like to upgrade these packages to up-to-date ones. Thanks.

![image](https://user-images.githubusercontent.com/1920873/85495313-d81f1580-b60c-11ea-93f5-46b2b401658b.png)

**Stack trace as follow:**

Launching lib/main.dart on iPad (7th generation) in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           15.0s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPad (7th generation).
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
lib/data/database/database.g.dart:10:7: Error: The non-abstract class 'TodoEntry' is missing implementations for these members:
 - Insertable.toColumns
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class TodoEntry extends DataClass implements Insertable<TodoEntry> {
      ^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart:22:27: Context: 'Insertable.toColumns' is defined here.
  Map<String, Expression> toColumns(bool nullToAbsent);
                          ^^^^^^^^^
lib/data/database/database.g.dart:104:7: Error: The non-abstract class 'TodosCompanion' is missing implementations for these members:
 - Insertable.toColumns
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class TodosCompanion extends UpdateCompanion<TodoEntry> {
      ^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart:22:27: Context: 'Insertable.toColumns' is defined here.
  Map<String, Expression> toColumns(bool nullToAbsent);
                          ^^^^^^^^^
lib/data/database/database.g.dart:252:7: Error: The non-abstract class 'Category' is missing implementations for these members:
 - Insertable.toColumns
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class Category extends DataClass implements Insertable<Category> {
      ^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart:22:27: Context: 'Insertable.toColumns' is defined here.
  Map<String, Expression> toColumns(bool nullToAbsent);
                          ^^^^^^^^^
lib/data/database/database.g.dart:316:7: Error: The non-abstract class 'CategoriesCompanion' is missing implementations for these members:
 - Insertable.toColumns
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CategoriesCompanion extends UpdateCompanion<Category> {
      ^^^^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart:22:27: Context: 'Insertable.toColumns' is defined here.
  Map<String, Expression> toColumns(bool nullToAbsent);
                          ^^^^^^^^^
lib/data/database/database.g.dart:191:56: Error: The parameter 'd' of the method '$TodosTable.validateIntegrity' has type 'TodosCompanion', which does not match the corresponding type, 'Insertable<TodoEntry>', in the overridden method, 'TableInfo.validateIntegrity'.
 - 'TodosCompanion' is from 'package:flutterapp2/data/database/database.dart' ('lib/data/database/database.dart').
 - 'Insertable' is from 'package:moor/src/runtime/data_class.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart').
 - 'TodoEntry' is from 'package:flutterapp2/data/database/database.dart' ('lib/data/database/database.dart').
Change to a supertype of 'Insertable<TodoEntry>', or, for a covariant parameter, a subtype.
  VerificationContext validateIntegrity(TodosCompanion d,
                                                       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/schema/table_info.dart:49:23: Context: This is the overridden method ('validateIntegrity').
  VerificationContext validateIntegrity(Insertable<D> instance,
                      ^
lib/data/database/database.g.dart:372:61: Error: The parameter 'd' of the method '$CategoriesTable.validateIntegrity' has type 'CategoriesCompanion', which does not match the corresponding type, 'Insertable<Category>', in the overridden method, 'TableInfo.validateIntegrity'.
 - 'CategoriesCompanion' is from 'package:flutterapp2/data/database/database.dart' ('lib/data/database/database.dart').
 - 'Insertable' is from 'package:moor/src/runtime/data_class.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/data_class.dart').
 - 'Category' is from 'package:flutterapp2/data/database/database.dart' ('lib/data/database/database.dart').
Change to a supertype of 'Insertable<Category>', or, for a covariant parameter, a subtype.
  VerificationContext validateIntegrity(CategoriesCompanion d,
                                                            ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/schema/table_info.dart:49:23: Context: This is the overridden method ('validateIntegrity').
  VerificationContext validateIntegrity(Insertable<D> instance,
                      ^
lib/data/database/database.g.dart:232:19: Error: Expected 1 type arguments.
      map['id'] = Variable<int, IntType>(d.id.value);
                  ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
lib/data/database/database.g.dart:235:24: Error: Expected 1 type arguments.
      map['content'] = Variable<String, StringType>(d.content.value);
                       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
lib/data/database/database.g.dart:238:28: Error: Expected 1 type arguments.
      map['target_date'] = Variable<DateTime, DateTimeType>(d.targetDate.value);
                           ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
lib/data/database/database.g.dart:241:25: Error: Expected 1 type arguments.
      map['category'] = Variable<int, IntType>(d.category.value);
                        ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
lib/data/database/database.g.dart:401:19: Error: Expected 1 type arguments.
      map['id'] = Variable<int, IntType>(d.id.value);
                  ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^
lib/data/database/database.g.dart:404:21: Error: Expected 1 type arguments.
      map['desc'] = Variable<String, StringType>(d.description.value);
                    ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.1.0/lib/src/runtime/query_builder/expressions/variables.dart:22:9: Context: Found this candidate, but the arguments don't match.
  const Variable(this.value);
        ^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by rodydavis** [comment]
I’ll see what I can do!

**Comment by simolus3** [comment]
I assume most of this will go away when upgrading `moor_generator` and re-running the build.

@rodydavis Are you working on this? Otherwise I can get a PR ready to upgrade moor dependencies.

**Comment by rodydavis** [comment]
@simolus3 you can make a PR and I’ll merge it!
