### ISSUE TITLE
Error resolving plugin [id: 'de.undercouch.download', version: '4.0.0']

### ISSUE THREAD

**Issue by jims57** [rodydavis/moor_shared#9]
I all platfroms such as iOS, MacOS, Web, work well with this project, except android, when I try to run this project on Android device(actually emulator), it throw the following exception. Can you help why? Thanks.

**-----------Stack trace-----------**
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.2.0/android/build.gradle' line: 13

* What went wrong:
Error resolving plugin [id: 'de.undercouch.download', version: '4.0.0']
> Plugin request for plugin already on the classpath must not include a version

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by rodydavis** [comment]
Oh interesting. 🧐 does this happen with SQLite package for flutter too?

**Comment by jims57** [comment]
@rodydavis No. In fact, at the beginning, I tried **Sqlite**, all work fine. But it show the above error after I changed the package to use **moor** instead of sqlite(removed sqlite related package in **pubspec.yaml**)

**Comment by jims57** [comment]
@rodydavis The bug is fixed now. I changed the **moor_ffi** from **0.2.0** to **0.30** according to the moor author suggests.

Bug I think you should investigate why **moor_shared** will raise the [error](https://github.com/rodydavis/moor_shared/issues/8) after I upgrade moor and moor_ffi to the latest version. I want to use the latest version, this may be worth looking at why, thanks.

**Comment by simolus3** [comment]
Yeah, this was a problem in old `moor_ffi` versions, but it's fixed in recent releases.

**Comment by jims57** [comment]
> Yeah, this was a problem in old `moor_ffi` versions, but it's fixed in recent releases.

Which version should I use, is it **moor_ffi 0.6.0**? If I am right, I once used **moor_ffi 0.6.0**(the latest version) has the [error](https://github.com/rodydavis/moor_shared/issues/8). I am not sure which project should be responsible for this, **moor** or **moor_shared** project.

**Comment by simolus3** [comment]
You can checkout https://github.com/rodydavis/moor_shared/pull/10 for a version that uses the latest moor packages and works. You can just upgrade moor and then run `flutter pub run build_runner build` to fix those errors.
